### ISSUE TITLE
Permission Denied after install

### ISSUE THREAD

**Issue by m3rl1n** [Jamesits/docker-dst-server#18] opened 2020-01-19 14:15 UTC
hey,

i try to install the docker on an qnap NAS with the command 
`docker run -v ${HOME}/.klei/DoNotStarveTogether:/data -p 10999-11000:10999-11000/udp -p 12346-12347:12346-12347/udp -it jamesits/dst-server:latest`

after downloading and installing i get the following error:

> updating mods...
su: warning: cannot change directory to /data: Permission denies
su: failed to execute /bin/sh: Permission denied
Error on line 50; RET 126.

is this a problem in combination with qnap?
or my fault?

**Comment by Jamesits** [comment] 2020-01-19 14:16
Please run `ls -alh ${HOME}/.klei/DoNotStarveTogether` and post your result.

**Comment by m3rl1n** [comment] 2020-01-19 14:28
> # ls -alh ${HOME}/.klei/DoNotStarveTogether
> total 0
> drwxr-xr-x 4 user docker         80 2020-01-19 12:04 ./
> drwxr-xr-x 3 admin  administrators 60 2020-01-19 12:04 ../
> drwxr-xr-x 3 user docker         60 2020-01-19 12:04 Agreements/
> drwxr-xr-x 3 user docker         60 2020-01-19 12:04 DoNotStarveTogether/

**Comment by Jamesits** [comment] 2020-01-19 14:41
Is your docker daemon mapping root inside the container to some other user?

**Comment by m3rl1n** [comment] 2020-01-19 15:06
No.

I think i understand my mistake... but i dont know how to fix it... 
do i have to change this part?
`${HOME}/.klei/DoNotStarveTogether:/data`

I tried it with an other directory with same error.
Now i definitly think its my fault ;).

**Comment by Jamesits** [comment] 2020-01-19 15:26
The path before the colon is where you want to store game data. It needs to be writable by uid 1000 in the container. Also the container needs root privilege to run (not the root on your OS, but the root inside the container.)

I don't have any QNAP devices to try it out, but I guess its docker daemon is applying some default security limitations to the container, and directory permissions are also not that good to my eyes. I'd like to know if there is any documentation on QNAP's docker implementation on these particular topics.

**Comment by m3rl1n** [comment] 2020-01-19 18:05
Okay thank you so far. 

Already changed the permissions but after starting the container the permissions changed back.. so i will check groups. The fact that the error comes so late in the script irritates me a bit cause the /data folder already called earlier in the script.

**Comment by m3rl1n** [comment] 2020-01-21 05:10
hey, im a step further.... after loading everything... i get the message:

> 2020-01-21 06:57:49,952 INFO exited: dst-server-master (exit status 1; not expected)                                                                                                                                                                                  
2020-01-21 06:57:50,953 INFO gave up: dst-server-master entered FATAL state, too many start retries too quickly

**Comment by Jamesits** [comment] 2020-01-21 05:12
Are there any other logs before that? Exit status 1 only means the server is quitting with errors. If possible, could you please post the full log?

**Comment by m3rl1n** [comment] 2020-01-21 18:07
sorry for the late response...

> 1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
[00:00:32]: Reset() returning                                                                                                                            
[00:00:32]: [Steam] SteamGameServer_Init(8767, 11000, 12347)                                                                                             
crypto.cpp (2388) : Fatal Assertion Failed: s_dev_urandom_fd >= 0                                                                                        
crypto.cpp (2388) : Fatal Assertion Failed: s_dev_urandom_fd >= 0                                                                                        
crypto.cpp (2388) : Fatal assert failed: crypto.cpp, line 2388.  Application exiting.

**Comment by Jamesits** [comment] 2020-01-22 04:56
So the steam client is complaining about not able to open `/dev/urandom`. That's very strange.

Please do the following:
```
docker run --name dst-test -dit jamesits/dst-server:latest
# wait 1-2 seconds
docker inspect dst-test > docker-inspect.txt
# remove the container
docker rm --force dst-test
```

and post the content of `docker-inspect.txt` here.

**Comment by m3rl1n** [comment] 2020-01-22 18:17
Hope this helps

> [
    {
        "Id": "5f8d9eb8d0ff3deba59617270832108dba969d8100f3bafd0e94ff80d4313b87",
        "Created": "2020-01-22T19:58:24.4114209Z",
        "Path": "entrypoint.sh",
        "Args": [
            "supervisord",
            "-c",
            "/etc/supervisor/supervisor.conf",
            "-n"
        ],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2020-01-22T19:58:26.03207908Z",
            "FinishedAt": "2020-01-22T19:58:26.582417324Z",
            "Health": {
                "Status": "unhealthy",
                "FailingStreak": 0,
                "Log": []
            }
        },
        "Image": "sha256:209e2b24184ee02eb917eb8e6d114328f34be0859e7a895b1f9341475952939a",
        "ResolvConfPath": "/share/MD0_DATA/Download/container-station-data/lib/docker/containers/5f8d9eb8d0ff3deba59617270832108dba969d8100f3bafd0e94ff80d4313b87/resolv.conf",
        "HostnamePath": "/share/MD0_DATA/Download/container-station-data/lib/docker/containers/5f8d9eb8d0ff3deba59617270832108dba969d8100f3bafd0e94ff80d4313b87/hostname",
        "HostsPath": "/share/MD0_DATA/Download/container-station-data/lib/docker/containers/5f8d9eb8d0ff3deba59617270832108dba969d8100f3bafd0e94ff80d4313b87/hosts",
        "LogPath": "/share/MD0_DATA/Download/container-station-data/lib/docker/containers/5f8d9eb8d0ff3deba59617270832108dba969d8100f3bafd0e94ff80d4313b87/5f8d9eb8d0ff3deba59617270832108dba969d8100f3bafd0e94ff80d4313b87-json.log",
        "Name": "/dst-test",
        "RestartCount": 0,
        "Driver": "overlay",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/share/MD0_DATA/Download/container-station-data/lib/docker/overlay/a3ce34f1ef7bfdd4412d13dc0357e944c538001d71f8d758cb017123e2bc4a78/root",
                "MergedDir": "/share/MD0_DATA/Download/container-station-data/lib/docker/overlay/99e3c63f56cd024f1d11fe44ab7d216c7772ec683a164a55682680b1d52a0471/merged",
                "UpperDir": "/share/MD0_DATA/Download/container-station-data/lib/docker/overlay/99e3c63f56cd024f1d11fe44ab7d216c7772ec683a164a55682680b1d52a0471/upper",
                "WorkDir": "/share/MD0_DATA/Download/container-station-data/lib/docker/overlay/99e3c63f56cd024f1d11fe44ab7d216c7772ec683a164a55682680b1d52a0471/work"
            },
            "Name": "overlay"
        },
        "Mounts": [
            {
                "Type": "volume",
                "Name": "45ee4e13926f1cb361baf2126e072ef74ecf9425673c57d8a3d1c836cde7973e",
                "Source": "/share/MD0_DATA/Download/container-station-data/lib/docker/volumes/45ee4e13926f1cb361baf2126e072ef74ecf9425673c57d8a3d1c836cde7973e/_data",
                "Destination": "/data",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "5f8d9eb8d0ff",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "10999/udp": {},
                "11000/udp": {},
                "12346/udp": {},
                "12347/udp": {}
            },
            "Tty": true,
            "OpenStdin": true,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "supervisord",
                "-c",
                "/etc/supervisor/supervisor.conf",
                "-n"
            ],
            "Healthcheck": {
                "Test": [
                    "CMD",
                    "healthcheck.sh"
                ],
                "Interval": 30000000000,
                "Timeout": 5000000000,
                "StartPeriod": 60000000000,
                "Retries": 3
            },
            "ArgsEscaped": true,
            "Image": "jamesits/dst-server:latest",
            "Volumes": {
                "/data": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "maintainer": "James Swineson <docker@public.swineson.me>"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "6d3d30aa0ef28125e3727bfab11c56b0b564c178bd65a79850077b8b9837717a",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/6d3d30aa0ef2",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "a6c5249b784dcb1d605be54bf81e8c6241d1c30d42424fadf1de8b8e3a72ac87",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]

**Comment by Jamesits** [comment] 2020-02-16 13:24
Hi,

Sorry for the late reply, I could not find any QNAP devices in a short time. Today I found there is a QNAP demo server on their website so I had some time debugging this issue on their hardware. 

By design the Container Station app is not allowed to access user home directory, so it is normal for you to have "permission denied" issues. I tried to mount a folder under my home directory into the container on web GUI, it didn't even show up in the file selector. I tried mounting some folder under `/Public` to the container and everything worked as expected. 

![](https://user-images.githubusercontent.com/1297257/74605347-47b15100-50bf-11ea-8fb0-80e0aa2f53e3.png)

P.S. I have the container's networking mode set to "host", otherwise (under the default "NAT" mode) I cannot download server updates from Steam CDN. I'm not sure if it is the demo server's network problem or a problem of QNAP OS.

**Comment by Jamesits** [comment] 2020-02-25 14:47
I'm closing this due to not receiving any feedback for some time. If you still have questions on this issue, feel free to re-open it.

**Closed by Jamesits** 2020-02-25 14:47 UTC

**Comment by m13253** [comment] 2024-08-13 18:09
If your Linux system has SELinux enabled. You need to add `:z` to the end of `-v`.
I am not sure if this is the case for QTS. But you might want to have a try.
```
docker run -v ${HOME}/.klei/DoNotStarveTogether:/data:z -p 10999-11000:10999-11000/udp -p 12346-12347:12346-12347/udp -e "DST_SERVER_ARCH=amd64" -it jamesits/dst-server:latest
```
